export const feedData = [
  {
    id: 1,
    profilePic: "https://i.pravatar.cc/300?img=18",
    username: "Newt Scamander",
    time: "15 min ago",
    imageUrls: [],
    title: "The Magic of Creatures",
    content:
      "Dogs remind me so much of magical creatures—loyal, intelligent, and always full of surprises. If you observe them closely, you’ll see a depth of emotion in their eyes, an unbreakable bond of trust, and an instinctive understanding of human emotions that even some wizards lack. I’ve traveled far and wide, encountering all sorts of fascinating creatures, but there is something truly special about the companionship of a dog. Their ability to comfort in times of sorrow, their enthusiasm for the smallest joys, and their unwavering courage in protecting those they love make them some of the most remarkable beings on this planet. If more people took the time to understand the creatures around them, magical or not, the world would be a much kinder place.",
    documentUrls: [],
    likeCount: "32",
    commentCount: "0",
    comments: [],
  },
  // Text + Attachment (Modified)
  {
    id: 2,
    profilePic: "https://i.pravatar.cc/300?img=22",
    username: "Sirius Black",
    time: "20 min ago",
    imageUrls: [],
    title: "A Dog’s Perspective",
    content:
      "Ever wondered what life looks like from a dog’s eyes? It’s all about loyalty, adventure, and chasing after what truly matters.",
    documentUrls: ["life-as-a-dog.pdf"],
    likeCount: "45",
    commentCount: "0",
    comments: [],
  },
  // Text + Photo (Modified)
  {
    id: 3,
    profilePic: "https://i.pravatar.cc/300?img=25",
    username: "Luna Lovegood",
    time: "30 min ago",
    imageUrls: ["https://placedog.net/600/400?id=31"],
    title: "Mystical Dogs",
    content:
      "Did you know some believe that dogs can sense energies beyond what we see? Maybe they really do guard us from unseen forces!",
    documentUrls: [],
    likeCount: "28",
    commentCount: "0",
    comments: [],
  },
  {
    id: 4,
    profilePic: "https://i.pravatar.cc/300?img=12",
    username: "Albus Dumbledore",
    time: "10 min ago",
    imageUrls: ["https://placedog.net/600/400?id=227"],
    title: "The Wisdom of Dogs",
    content:
      "Dogs are not just pets; they are family. Their loyalty, love, and joy are reminders of the simple pleasures in life. Never underestimate the power of a wagging tail.",
    documentUrls: ["dog-care-guide.docx"],
    likeCount: "25",
    commentCount: "2",
    comments: [
      {
        id: 1,
        profilePic: "https://i.pravatar.cc/300?img=20",
        username: "Minerva McGonagall",
        time: "5 min ago",
        text: "I completely agree, Headmaster. A dog’s loyalty is unmatched. My cat, however, is a bit more independent! 🐱",
      },
      {
        id: 2,
        profilePic: "https://i.pravatar.cc/300?img=21",
        username: "Severus Snape",
        time: "2 min ago",
        text: "Hmph. Dogs are overrated. Give me a good potion any day.",
      },
    ],
  },
  {
    id: 5,
    profilePic: "https://i.pravatar.cc/300?img=5",
    username: "Harry Potter",
    time: "20 min ago",
    imageUrls: [
      "https://placedog.net/600/400?id=18",
      "https://placedog.net/600/400?id=30",
    ],
    title: "The Joy of Dog Walking",
    content:
      "Today, I took my dog for a long walk in the park. Dogs have such an infectious energy. They can turn even a bad day into something amazing. Let’s not forget to appreciate them.",
    contentToggle: false,
    documentUrls: ["dog-walking-tips-1.pdf", "dog-walking-tips-2.pdf"],
    likeCount: "40",
    commentCount: "2",
    comments: [
      {
        id: 1,
        profilePic: "https://i.pravatar.cc/300?img=8",
        username: "Ginny Weasley",
        time: "10 min ago",
        text: "I love taking my dog to the park! It's always the highlight of my day. 🐕",
      },
      {
        id: 2,
        profilePic: "https://i.pravatar.cc/300?img=10",
        username: "Draco Malfoy",
        time: "5 min ago",
        text: "Dogs are overrated. Cats are where it’s at. They don’t drool everywhere.",
      },
    ],
  },
  {
    id: 6,
    profilePic: "https://i.pravatar.cc/300?img=11",
    username: "Hermione Granger",
    time: "1 hour ago",
    imageUrls: [
      "https://placedog.net/600/400?id=43",
      "https://placedog.net/600/400?id=77",
      "https://placedog.net/600/400?id=81",
    ],
    title: "Dogs and Reading 📚",
    content:
      "Dogs are always there to keep us company while we read. I think I’ve read more books with my dog by my side than without! It’s amazing how they just sit there quietly, waiting for you to finish.",
    documentUrls: ["dog-friendly-books.pdf"],
    likeCount: "30",
    commentCount: "2",
    comments: [
      {
        id: 1,
        profilePic: "https://i.pravatar.cc/300?img=22",
        username: "Luna Lovegood",
        time: "30 min ago",
        text: "Dogs are great companions. Have you ever read about magical dogs in Muggle literature? I think there's a breed called the Basenji!",
      },
      {
        id: 2,
        profilePic: "https://i.pravatar.cc/300?img=23",
        username: "Neville Longbottom",
        time: "20 min ago",
        text: "I think dogs are even better than books sometimes. My dog always knows when I need a break from studying!",
      },
    ],
  },
  {
    id: 7,
    profilePic: "https://i.pravatar.cc/300?img=4",
    username: "Ron Weasley",
    time: "3 hours ago",
    imageUrls: [
      "https://placedog.net/600/400?id=82",
      "https://placedog.net/600/400?id=87",
      "https://placedog.net/600/400?id=95",
      "https://placedog.net/600/400?id=114",
    ],
    title: "Best Dog Moment Ever!",
    content:
      "I finally taught my dog to fetch the newspaper. It’s the little things that make me proud. Next step: teaching him how to cook breakfast! 🥞",
    documentUrls: ["dog-training-tips.pdf"],
    likeCount: "15",
    commentCount: "2",
    comments: [
      {
        id: 1,
        profilePic: "https://i.pravatar.cc/300?img=6",
        username: "Fred Weasley",
        time: "2 hours ago",
        text: "Did you teach him to clean up after himself too? 😆",
      },
      {
        id: 2,
        profilePic: "https://i.pravatar.cc/300?img=7",
        username: "George Weasley",
        time: "1 hour ago",
        text: "We should teach our dogs how to prank people. Imagine the chaos they could cause! 😂",
      },
    ],
  },
  {
    id: 8,
    profilePic: "https://i.pravatar.cc/300?img=14",
    username: "Hagrid",
    time: "5 hours ago",
    imageUrls: [
      "https://placedog.net/1000/400?id=217",
      "https://placedog.net/400/400?id=220",
      "https://placedog.net/600/1000?id=222",
      "https://placedog.net/600/400?id=233",
      "https://placedog.net/600/400?id=238",
    ],
    title: "My Love for Big Dogs",
    content:
      "There's nothin' better than a big ol' dog to keep ya company. Fang is the best boy ever! Loyal, brave, and always ready for an adventure!",
    documentUrls: ["big-dog-care.pdf"],
    likeCount: "50",
    commentCount: "2",
    comments: [
      {
        id: 1,
        profilePic: "https://i.pravatar.cc/300?img=30",
        username: "Sirius Black",
        time: "4 hours ago",
        text: "Big dogs are the best! I might be biased, though... 🐶",
      },
      {
        id: 2,
        profilePic: "https://i.pravatar.cc/300?img=31",
        username: "Remus Lupin",
        time: "3 hours ago",
        text: "Fang is a legend. Always happy to see him running around Hogwarts!",
      },
    ],
  },
];
