import { getLastActivityAgo } from "@/utils/datetime";

export interface UnassignStudentModel {
    id : number,
    first_name: string,
    middle_name?: string | null,
    last_name? : string | null,
    email : string ,
    date_of_birth? : string | null,
    nationality? : string | null,
    gender? : string | null,
    address? : string | null,
    phone_number? : string | null,
    passport?: string | null,
    status? : string | null,
    role? : {
        id ?: number | null,
        name? : string | null,
    },
    image_id? : any | null,
    email_verified_at?: string | null,
    profile_picture?: string | null,
    activity_logs? : {
        id? : number | null,
        user_id?: number | null,
        visit_count? : number | null,
        ip_address? : number | null,
        session_login? : string | null,
        session_logout? : string | null,
        created_at? : string | null,
        updated_at? : string | null,
        deleted_at? : string | null,
        last_activity_at? : string | null,
    },
    student? : {
        id? : number | null,
        major_id? : number | null,
        emergency_contact_name? : string | null,
        emergency_contact_phone? : string | null,
        enrollment_date? : string | null,
        graduation_date? : string | null,
        current_year? : string | null,
    },
    tutoring_sessions?: any[] | null,
    tutoring_session_status? : string | null,
    created_at? : string | null,
    updated_at? : string | null,
    getLastActivity : string,
};


export function unassignedStudentFromJson(jsonData : any) : UnassignStudentModel {
    return  {
        id : jsonData.id,
        first_name: jsonData.first_name,
        middle_name: jsonData.middle_name,
        last_name : jsonData.last_name,
        email : jsonData.email,
        date_of_birth : jsonData.date_of_birth,
        nationality : jsonData.nationality,
        gender : jsonData.gender,
        address : jsonData.address,
        phone_number : jsonData.phone_number,
        passport: jsonData.passport,
        status : jsonData.status,
        role : {
            id: jsonData.role.id,
            name : jsonData.role.name,
        },
        image_id : jsonData.image_id,
        email_verified_at : jsonData.email_verified_at,
        profile_picture : jsonData.profile_picture,
        activity_logs : {
            id : jsonData.activity_logs?.id,
            user_id: jsonData.activity_logs?.user_id,
            visit_count : jsonData.visit_count,
            ip_address : jsonData.activity_logs?.ip_address,
            session_login : jsonData.activity_logs?.session_login,
            session_logout : jsonData.activity_logs?.session_logout,
            created_at : jsonData.activity_logs?.created_at,
            updated_at : jsonData.activity_logs?.updated_at,
            deleted_at : jsonData.activity_logs?.deleted_at,
            last_activity_at : jsonData.activity_logs?.last_activity_at,
        },
        student : {
            id : jsonData.student?.id,
            major_id : jsonData.student?.major_id,
            emergency_contact_name : jsonData.student?.emergency_contact_name,
            emergency_contact_phone : jsonData.student?.emergency_contact_phone,
            enrollment_date : jsonData.student?.enrollment_date,
            graduation_date : jsonData.student?.graduation_date,
            current_year : jsonData.student?.current_year,
        },
        tutoring_sessions: jsonData.tutoring_sessions,
        tutoring_session_status : jsonData.tutoring_session_status,
        created_at : jsonData.created_at,
        updated_at : jsonData.updated_at,
        getLastActivity : getLastActivityAgo(jsonData.activity_logs)
    };
}