// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
"use client";

import { errorStore } from "@/stores/errorStore";
import "./../styles/globals.css";
import ToggleTheme from "./components/toggleTheme";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { setError } = errorStore();

  return (
    <html lang="en">
      <body className={``}>
        <div className="flex gap-5 m-3">
          <ToggleTheme />
          <div>
            <button
              onClick={() => setError("Login Failed!")}
              className="p-2 rounded-md border transition duration-300 bg-white text-black"
            >
              Show Error
            </button>
          </div>
        </div>
        <div
          className={`w-full h-[500px] bg-background text-font transition-all duration-500`}
        >
          Layout
        </div>
        {children}
      </body>
    </html>
  );
}
