import { Meeting } from "@/model/meeting";

export const activeMeetingData: Meeting[] = [
  {
    id: 1,
    creator_id: 3,
    subject: "Database Management Systems",
    date: "2025-03-15",
    time: "10:00 AM",
    type: "In-Person",
    location: "Conference Room 1, Building A",
    platform: null,
    link: null,
    creator: {
      id: 3,
      name: "David Brown",
      email: "db5769608@gmail.com",
      profile_picture: null,
    },
    participants: [
      {
        id: 3,
        name: "David Brown",
        email: "db5769608@gmail.com",
      },
      {
        id: 7,
        name: "Evelyn Sik",
        email: "evelynsik4@gmail.com",
      },
      {
        id: 8,
        name: "Olivia Thomas",
        email: "olivia.thomas@example.com",
      },
      {
        id: 9,
        name: "Noah Martinez",
        email: "noah.martinez@example.com",
      },
      {
        id: 10,
        name: "Emma Harris",
        email: "emma.harris@example.com",
      },
      {
        id: 11,
        name: "William Clark",
        email: "william.clark@example.com",
      },
      {
        id: 12,
        name: "Ava Lewis",
        email: "ava.lewis@example.com",
      },
      {
        id: 13,
        name: "James Young",
        email: "james.young@example.com",
      },
      {
        id: 14,
        name: "Sophia King",
        email: "sophia.king@example.com",
      },
      {
        id: 15,
        name: "Benjamin Walker",
        email: "benjamin.walker@example.com",
      },
      {
        id: 16,
        name: "Mia Hall",
        email: "mia.hall@example.com",
      },
    ],
  },
  {
    id: 2,
    creator_id: 3,
    subject: "Database Management Systems",
    date: "2025-03-15",
    time: "10:00 AM",
    type: "In-Person",
    location: "Conference Room 1, Building A",
    platform: null,
    link: null,
    creator: {
      id: 3,
      name: "David Brown",
      email: "db5769608@gmail.com",
      profile_picture: null,
    },
    participants: [
      {
        id: 3,
        name: "David Brown",
        email: "db5769608@gmail.com",
      },
      {
        id: 7,
        name: "Evelyn Sik",
        email: "evelynsik4@gmail.com",
      },
      {
        id: 8,
        name: "Olivia Thomas",
        email: "olivia.thomas@example.com",
      },
      {
        id: 9,
        name: "Noah Martinez",
        email: "noah.martinez@example.com",
      },
      {
        id: 10,
        name: "Emma Harris",
        email: "emma.harris@example.com",
      },
      {
        id: 11,
        name: "William Clark",
        email: "william.clark@example.com",
      },
      {
        id: 12,
        name: "Ava Lewis",
        email: "ava.lewis@example.com",
      },
      {
        id: 13,
        name: "James Young",
        email: "james.young@example.com",
      },
      {
        id: 14,
        name: "Sophia King",
        email: "sophia.king@example.com",
      },
      {
        id: 15,
        name: "Benjamin Walker",
        email: "benjamin.walker@example.com",
      },
      {
        id: 16,
        name: "Mia Hall",
        email: "mia.hall@example.com",
      },
    ],
  },
  {
    id: 3,
    creator_id: 3,
    subject: "Database Management Systems",
    date: "2025-03-15",
    time: "10:00 AM",
    type: "Online",
    location: null,
    platform: "Zoom",
    link: null,
    creator: {
      id: 3,
      name: "David Brown",
      email: "db5769608@gmail.com",
      profile_picture: null,
    },
    participants: [
      {
        id: 3,
        name: "David Brown",
        email: "db5769608@gmail.com",
      },
    ],
  },
  {
    id: 4,
    creator_id: 3,
    subject: "Database Management Systems",
    date: "2025-03-15",
    time: "10:00 AM",
    type: "Online",
    location: null,
    platform: "Teams",
    link: null,
    creator: {
      id: 3,
      name: "David Brown",
      email: "db5769608@gmail.com",
      profile_picture: null,
    },
    participants: [
      {
        id: 3,
        name: "David Brown",
        email: "db5769608@gmail.com",
      },
    ],
  },
  {
    id: 5,
    creator_id: 3,
    subject: "Database Management Systems",
    date: "2025-03-15",
    time: "10:00 AM",
    type: "Online",
    location: null,
    platform: "Google Meet",
    link: null,
    creator: {
      id: 3,
      name: "David Brown",
      email: "db5769608@gmail.com",
      profile_picture: null,
    },
    participants: [
      {
        id: 3,
        name: "David Brown",
        email: "db5769608@gmail.com",
      },
    ],
  },
  {
    id: 6,
    creator_id: 3,
    subject: "Database Management Systems",
    date: "2025-03-15",
    time: "10:00 AM",
    type: "Online",
    location: null,
    platform: "Other",
    link: null,
    creator: {
      id: 3,
      name: "David Brown",
      email: "db5769608@gmail.com",
      profile_picture: null,
    },
    participants: [
      {
        id: 3,
        name: "David Brown",
        email: "db5769608@gmail.com",
      },
    ],
  },
  {
    id: 7,
    creator_id: 3,
    subject: "Database Management Systems",
    date: "2025-03-15",
    time: "10:00 AM",
    type: "Online",
    location: null,
    platform: "Other",
    link: null,
    creator: {
      id: 3,
      name: "David Brown",
      email: "db5769608@gmail.com",
      profile_picture: null,
    },
    participants: [
      {
        id: 3,
        name: "David Brown",
        email: "db5769608@gmail.com",
      },
    ],
  },
  {
    id: 8,
    creator_id: 3,
    subject: "Database Management Systems",
    date: "2025-03-15",
    time: "10:00 AM",
    type: "Online",
    location: null,
    platform: "Other",
    link: null,
    creator: {
      id: 3,
      name: "David Brown",
      email: "db5769608@gmail.com",
      profile_picture: null,
    },
    participants: [
      {
        id: 3,
        name: "David Brown",
        email: "db5769608@gmail.com",
      },
    ],
  },
];

export const historyMeetingData: Meeting[] = [
  {
    id: 2,
    creator_id: 3,
    subject: "Database Management Systems",
    date: "2025-03-15",
    time: "10:00 AM",
    type: "In-Person",
    location: "Conference Room 1, Building A",
    platform: null,
    link: null,
    creator: {
      id: 3,
      name: "David Brown",
      email: "db5769608@gmail.com",
      profile_picture: null,
    },
    participants: [
      {
        id: 3,
        name: "David Brown",
        email: "db5769608@gmail.com",
      },
      {
        id: 7,
        name: "Evelyn Sik",
        email: "evelynsik4@gmail.com",
      },
      {
        id: 8,
        name: "Olivia Thomas",
        email: "olivia.thomas@example.com",
      },
      {
        id: 9,
        name: "Noah Martinez",
        email: "noah.martinez@example.com",
      },
      {
        id: 10,
        name: "Emma Harris",
        email: "emma.harris@example.com",
      },
      {
        id: 11,
        name: "William Clark",
        email: "william.clark@example.com",
      },
      {
        id: 12,
        name: "Ava Lewis",
        email: "ava.lewis@example.com",
      },
      {
        id: 13,
        name: "James Young",
        email: "james.young@example.com",
      },
      {
        id: 14,
        name: "Sophia King",
        email: "sophia.king@example.com",
      },
      {
        id: 15,
        name: "Benjamin Walker",
        email: "benjamin.walker@example.com",
      },
      {
        id: 16,
        name: "Mia Hall",
        email: "mia.hall@example.com",
      },
    ],
  },
  {
    id: 3,
    creator_id: 3,
    subject: "Database Management Systems",
    date: "2025-03-15",
    time: "10:00 AM",
    type: "Online",
    location: null,
    platform: "Zoom",
    link: null,
    creator: {
      id: 3,
      name: "David Brown",
      email: "db5769608@gmail.com",
      profile_picture: null,
    },
    participants: [
      {
        id: 3,
        name: "David Brown",
        email: "db5769608@gmail.com",
      },
    ],
  },
  {
    id: 4,
    creator_id: 3,
    subject: "Database Management Systems",
    date: "2025-03-15",
    time: "10:00 AM",
    type: "Online",
    location: null,
    platform: "Teams",
    link: null,
    creator: {
      id: 3,
      name: "David Brown",
      email: "db5769608@gmail.com",
      profile_picture: null,
    },
    participants: [
      {
        id: 3,
        name: "David Brown",
        email: "db5769608@gmail.com",
      },
    ],
  },
  {
    id: 5,
    creator_id: 3,
    subject: "Database Management Systems",
    date: "2025-03-15",
    time: "10:00 AM",
    type: "Online",
    location: null,
    platform: "Google Meet",
    link: null,
    creator: {
      id: 3,
      name: "David Brown",
      email: "db5769608@gmail.com",
      profile_picture: null,
    },
    participants: [
      {
        id: 3,
        name: "David Brown",
        email: "db5769608@gmail.com",
      },
    ],
  },
  {
    id: 6,
    creator_id: 3,
    subject: "Database Management Systems",
    date: "2025-03-15",
    time: "10:00 AM",
    type: "Online",
    location: null,
    platform: "Other",
    link: null,
    creator: {
      id: 3,
      name: "David Brown",
      email: "db5769608@gmail.com",
      profile_picture: null,
    },
    participants: [
      {
        id: 3,
        name: "David Brown",
        email: "db5769608@gmail.com",
      },
    ],
  },
];
